"""1

Revision ID: 9174afc41627
Revises: 
Create Date: 2023-12-28 16:45:19.587145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9174afc41627'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'room_id')
    )
    op.alter_column('rooms', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('current_room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'rooms', ['current_room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'current_room_id')
    op.alter_column('rooms', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('association_table')
    # ### end Alembic commands ###
